# Generated by Django 3.1.5 on 2021-01-22 08:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userInfo', '0005_auto_20210120_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField()),
                ('like', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('nickname_info', models.CharField(default='', max_length=150)),
                ('information', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userInfo.profile')),
            ],
        ),
    ]
