# Generated by Django 3.1.5 on 2021-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210122_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='information',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='user',
        ),
        migrations.AddField(
            model_name='premium',
            name='infomation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='user_id',
            field=models.IntegerField(default=True),
        ),
    ]
