# Generated by Django 3.1.5 on 2021-01-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210122_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='profileImage',
            field=models.CharField(default='/media/red.jpg', max_length=500),
        ),
    ]
