# Generated by Django 3.1.5 on 2021-01-26 11:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiumst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField()),
                ('like', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('profileImage', models.CharField(default='/media/red.jpg', max_length=500)),
                ('user_id', models.IntegerField(default=True)),
                ('infomation', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField()),
                ('like', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(default='', max_length=200)),
                ('profileImage', models.CharField(default='/media/red.jpg', max_length=500)),
                ('user_id', models.IntegerField(default=True)),
                ('infomation', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
