# Generated by Django 3.1.5 on 2021-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_premiumst_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='premiumst',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
    ]
