# Generated by Django 3.1.5 on 2021-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210127_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='profileImage',
            field=models.CharField(default='/media/basic.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='premium',
            name='profileImage',
            field=models.CharField(default='/media/basic.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='premiumst',
            name='profileImage',
            field=models.CharField(default='/media/basic.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='profileImage',
            field=models.CharField(default='/media/basic.jpg', max_length=500),
        ),
    ]
