# Generated by Django 3.1.5 on 2021-01-20 05:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='profile/image/basic.jpg', upload_to='profile/image'),
        ),
    ]
