# Generated by Django 3.1.5 on 2021-01-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_auto_20210120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/image/basic.jpg', upload_to='profile/image'),
        ),
    ]
