# Generated by Django 3.1.5 on 2021-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0005_auto_20210120_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
