# Generated by Django 3.1.5 on 2021-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0007_auto_20210127_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
    ]
