# Generated by Django 3.1.5 on 2021-01-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0008_profile_likeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likedUser',
        ),
    ]
